spring:
  application:
  name: SpringAi

  ai:
    openai:
      # your openai key
      api-key: ${My_openAi_Key}
      # base url
      base-url: https://api.openai.com/

      # settings for chat api
      chat:
        options:
          temperature: 0.5 # 0.0 to 1.0 (higher is more creative)
          model: gpt-3.5-turbo # gpt-3.5-turbo or gpt-4-32k

      # settings for image generation api
        image:
            options:
            model: gpt-4-dalle
            height: 1024
            width: 1024
            quality: hd #the resolution of the image


