spring:
  application:
  name: SpringAi
  ai:
    openai:
      # your openai key
      api-key: ${My_openAi_Key}
      # choose your model
      engine-id: gpt-3.5-turbo
      # base url
      base-url: https://api.openai.com/


